name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './crossword-collab/package-lock.json'
    
    - name: Install Dependencies
      working-directory: ./crossword-collab
      run: npm ci
    
    - name: Lint
      working-directory: ./crossword-collab
      run: npm run lint -- --max-warnings=0
    
    - name: Type Check
      working-directory: ./crossword-collab
      run: npx tsc --noEmit
    
    - name: Run Tests
      working-directory: ./crossword-collab
      run: npm test 